import { StyleSheet } from 'react-native';
import { Colors } from './colors';

export const chatStyles = StyleSheet.create({
  background: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  container: {
    flex: 1,
    backgroundColor: 'transparent',
    marginTop: 50,
  },
  header: {
    alignItems: 'center',
    paddingTop: 30,
    paddingBottom: 10,
    backgroundColor: 'transparent',
  },
  avatar: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 3,
    borderColor: Colors.themeYellow,
    marginTop: -5,
  },
  messagesWrapper: {
    flex: 1,
    paddingHorizontal: 16,
    backgroundColor: 'transparent',
  },
  messagesContainer: {
    paddingVertical: 10,
    backgroundColor: 'transparent',
    // REMOVE flexGrow and paddingBottom here!
  },
  systemBubble: {
    backgroundColor: Colors.themeBrownDark,
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginVertical: 4,
    alignSelf: 'flex-start',
    maxWidth: '80%',
    shadowColor: Colors.shadow,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  userBubble: {
    backgroundColor: Colors.themeGreen,
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginVertical: 4,
    alignSelf: 'flex-end',
    maxWidth: '80%',
    shadowColor: Colors.shadow,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  bubbleText: {
    color: Colors.themeYellow,
    fontSize: 18,
    lineHeight: 24,
  },
  inputBar: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    backgroundColor: Colors.themeGreen,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    minHeight: 60,
  },
  input: {
    flex: 1,
    color: Colors.themeYellow,
    fontSize: 18,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: Colors.themeGreenMedium,
    borderRadius: 32,
    marginRight: 10,
    maxHeight: 100,
    textAlignVertical: 'top',
  },
  sendButton: {
    backgroundColor: Colors.themeGreenMedium,
    borderRadius: 24,
    padding: 12,
    alignSelf: 'flex-end',
    marginBottom: 2,
  },
  sendText: {
    fontSize: 20,
    color: Colors.themeYellow,
  },
  // New chat button ('+' icon on top right)
  newChatButton: {
    position: 'absolute',
    top: 60,
    right: 20,
    zIndex: 10,
    backgroundColor: Colors.themeYellow,
    borderRadius: 25,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: Colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 3,
  },
  newChatIcon: {
    fontSize: 28,
    color: Colors.themeBrownDark,
    fontWeight: '600',
    lineHeight: 30,
    textAlign: 'center',
  },
  // Voice icon for voice-originated messages
  voiceIcon: {
    fontSize: 14,
  },
});