import { StyleSheet } from 'react-native';

export const chatStyles = StyleSheet.create({
  background: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  container: {
    flex: 1,
    backgroundColor: 'transparent',
    marginTop: 50,
  },
  header: {
    alignItems: 'center',
    paddingTop: 30,
    paddingBottom: 10,
    backgroundColor: 'transparent',
  },
  avatar: {
    width: 150,
    height: 150,
    borderRadius: 75,
    borderWidth: 4,
    borderColor: '#fbe8c9',
    marginTop: 10,
  },
  messagesWrapper: {
    flex: 1,
    paddingHorizontal: 16,
    backgroundColor: 'transparent',
  },
  messagesContainer: {
    paddingVertical: 10,
    backgroundColor: 'transparent',
    // REMOVE flexGrow and paddingBottom here!
  },
  systemBubble: {
    backgroundColor: '#D68F20',
    borderRadius: 24,
    padding: 16,
    marginVertical: 10,
    alignSelf: 'flex-start',
    maxWidth: '80%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  userBubble: {
    backgroundColor: '#265C2E',
    borderRadius: 24,
    padding: 16,
    marginVertical: 10,
    alignSelf: 'flex-end',
    maxWidth: '80%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  bubbleText: {
    color: '#fbe8c9',
    fontSize: 18,
    lineHeight: 24,
  },
  inputBar: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    backgroundColor: '#265C2E',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    minHeight: 60,
  },
  input: {
    flex: 1,
    color: '#fbe8c9',
    fontSize: 18,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#3E7A4A',
    borderRadius: 32,
    marginRight: 10,
    maxHeight: 100,
    textAlignVertical: 'top',
  },
  sendButton: {
    backgroundColor: '#3E7A4A',
    borderRadius: 24,
    padding: 12,
    alignSelf: 'flex-end',
    marginBottom: 2,
  },
  sendText: {
    fontSize: 20,
    color: '#fbe8c9',
  },
});