import { StyleSheet } from 'react-native';
import { Colors } from './colors';

export const teamRandomizerStyles = StyleSheet.create({
  background: {
    flex: 1,
    resizeMode: 'cover',
    justifyContent: 'center',
    padding: 20,
  },
  container: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginTop: 100,
  },
  inlineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '90%',
    marginTop: 10,
  },
  title: {
    fontSize: 25,
    fontWeight: 'bold',
    color: Colors.teamTitleYellow,
    marginRight: 10,
  },
  inlinePicker: {
    width: 50,
    height: 40,
    backgroundColor: Colors.teamTitleYellow,
    borderRadius: 8,
  },
  nameInputs: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginTop: 25,
  },
  nameInput: {
    backgroundColor: Colors.teamTitleYellow,
    padding: 10,
    margin: 5,
    width: 90,
    borderRadius: 10,
    textAlign: 'center',
  },
  nameInputWide: {
    width: 150,
  },
  randomizeButton: {
    backgroundColor: Colors.wheelGreen,
    paddingVertical: 20,
    paddingHorizontal: 30,
    borderRadius: 15,
    marginTop: 50,
    marginHorizontal: 20,
    alignSelf: 'stretch',
    alignItems: 'center',
    elevation: 4,
  },
  randomizeText: {
    fontSize: 25,
    fontWeight: 'bold',
    color: Colors.white,
  },
  teamsContainer: {
    marginTop: 30,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  teamCard: {
    backgroundColor: Colors.teamCardBackground,
    padding: 15,
    borderRadius: 15,
    margin: 10,
    minWidth: 140,
    elevation: 10,
    shadowColor: Colors.shadow,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.5,
    shadowRadius: 12,
    transform: [{ rotate: '-2deg' }],
    alignItems: 'center',
    position: 'relative',
  },
  cardLeft: {
    transform: [{ rotate: '-4deg' }],
  },
  cardRight: {
    transform: [{ rotate: '4deg' }],
  },
  teamTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
    textAlign: 'center',
    color: Colors.teamText,
  },
  playerName: {
    fontSize: 18,
    textAlign: 'center',
    color: Colors.teamText,
  },
  pinDot: {
    width: 14,
    height: 14,
    backgroundColor: Colors.red,
    borderRadius: 7,
    position: 'absolute',
    top: 8,
    alignSelf: 'center',
    zIndex: 10,
    borderWidth: 1,
    borderColor: Colors.redPin,
    shadowColor: Colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.6,
    shadowRadius: 2,
  },
});
