import { StyleSheet } from 'react-native';
import { Colors } from './colors';

export const turnTrackerStyles = StyleSheet.create({
  background: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  container: {
    flex: 1,
    paddingTop: 60,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  pageHeader: {
    position: 'absolute',
    top: 57,
    left: 0,
    right: 0,
    zIndex: 9,
    fontSize: 32,
    fontWeight: '700',
    color: Colors.themeYellow,
    textAlign: 'center',
    textShadowColor: Colors.black,
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  subtitle: {
    fontSize: 18,
    fontWeight: '600',
    color: Colors.themeYellow,
    textAlign: 'center',
    marginTop: 8,
    marginBottom: 12,
    textShadowColor: Colors.black,
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  groupPickerWrap: {
    width: '100%',
    paddingHorizontal: 8,
  },
  // ── Seating circle ──────────────────────────────────────────
  circleWrap: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 8,
  },
  circleStage: {
    position: 'relative',
    alignSelf: 'center',
  },
  // ── Seats ──────────────────────────────────────────────────
  seatContainer: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  seatCircle: {
    backgroundColor: Colors.teamCardBackground,
    borderWidth: 2,
    borderColor: Colors.themeBrownDark,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.35,
    shadowRadius: 6,
    elevation: 6,
  },
  seatCircleEmpty: {
    backgroundColor: 'transparent',
    borderStyle: 'dashed',
    borderColor: Colors.themeYellow,
  },
  seatCircleActive: {
    borderColor: Colors.themeYellow,
    borderWidth: 4,
    shadowColor: Colors.themeYellow,
    shadowOpacity: 1,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 0 },
    elevation: 12,
  },
  seatInitials: {
    fontSize: 22,
    fontWeight: '800',
    color: Colors.themeBrownDark,
  },
  seatPlaceholderText: {
    fontSize: 28,
    fontWeight: '800',
    color: Colors.themeYellow,
  },
  seatLabel: {
    position: 'absolute',
    fontSize: 12,
    fontWeight: '700',
    color: Colors.themeYellow,
    textAlign: 'center',
    textShadowColor: Colors.black,
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  // ── Marker ─────────────────────────────────────────────────
  markerTouchable: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  // ── Direction toggle ───────────────────────────────────────
  toggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
    backgroundColor: 'rgba(0,0,0,0.35)',
    borderRadius: 22,
    padding: 4,
    borderWidth: 1,
    borderColor: Colors.themeYellow,
  },
  toggleSegment: {
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 18,
  },
  toggleSegmentActive: {
    backgroundColor: Colors.themeYellow,
  },
  toggleText: {
    fontSize: 14,
    fontWeight: '700',
    color: Colors.themeYellow,
  },
  toggleTextActive: {
    color: Colors.themeBrownDark,
  },
  // ── Primary CTAs ───────────────────────────────────────────
  primaryButton: {
    backgroundColor: Colors.themeGreen,
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 28,
    minWidth: 200,
    alignItems: 'center',
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 6,
    marginTop: 12,
    borderWidth: 2,
    borderColor: Colors.themeYellow,
  },
  primaryButtonDisabled: {
    backgroundColor: Colors.grayDisabled,
    borderColor: Colors.grayLight,
  },
  primaryButtonText: {
    fontSize: 18,
    fontWeight: '800',
    color: Colors.themeYellow,
  },
  // ── In-game CTA row (Add Game Score / Timer) ───────────────
  ctaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
    marginTop: 14,
    paddingHorizontal: 8,
  },
  ctaButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.wheelGreen,
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 10,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.35,
    shadowRadius: 5,
    elevation: 5,
  },
  ctaButtonAlt: {
    backgroundColor: Colors.wheelOrange,
  },
  ctaButtonText: {
    color: Colors.white,
    fontSize: 15,
    fontWeight: '800',
    marginLeft: 6,
  },
  endGameButton: {
    backgroundColor: 'transparent',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 22,
    marginTop: 14,
    borderWidth: 2,
    borderColor: Colors.timerRed,
    alignItems: 'center',
  },
  endGameText: {
    color: Colors.timerRed,
    fontSize: 15,
    fontWeight: '700',
  },
  // ── Bottom toolbar ─────────────────────────────────────────
  // (The toolbar component was removed in favour of in-flow CTA buttons.)
  // ── Lock helper text on in-game GroupPicker row ────────────
  lockHelper: {
    color: Colors.themeYellow,
    fontSize: 12,
    fontStyle: 'italic',
    textAlign: 'center',
    marginTop: 4,
    opacity: 0.85,
  },
  // ── Player picker modal ────────────────────────────────────
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalCard: {
    backgroundColor: '#2a1a0a',
    borderRadius: 12,
    width: '85%',
    maxHeight: '70%',
    borderWidth: 2,
    borderColor: Colors.themeYellow,
    overflow: 'hidden',
  },
  modalHeader: {
    color: Colors.themeYellow,
    fontSize: 18,
    fontWeight: 'bold',
    padding: 16,
    textAlign: 'center',
  },
  modalRow: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(251, 232, 201, 0.1)',
  },
  modalRowDisabled: {
    opacity: 0.4,
  },
  modalRowSelected: {
    backgroundColor: 'rgba(251, 232, 201, 0.18)',
  },
  modalRowText: {
    color: Colors.themeYellow,
    fontSize: 16,
  },
  modalRowSubtext: {
    color: Colors.grayDark,
    fontSize: 12,
    marginTop: 2,
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 12,
    borderTopWidth: 1,
    borderTopColor: 'rgba(251, 232, 201, 0.15)',
  },
  modalActionText: {
    color: Colors.themeYellow,
    fontSize: 15,
    fontWeight: '700',
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  modalActionDanger: {
    color: Colors.timerRed,
  },
});
