trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  apiProject: 'services/api/GamerUncle.Api.csproj'
  functionAppProject: 'services/functions/GamerUncle.Function.BggSync/GamerUncle.Function.BggSync.csproj'
  publishOutputApiProject: '$(Build.ArtifactStagingDirectory)/publish/api'
  publishOutputFunctionProject: '$(Build.ArtifactStagingDirectory)/publish/function'

stages:
- stage: DevBuild
  displayName: 'Dev Build'
  jobs:
  - job: BuildJob
    displayName: 'Build and Publish Artifacts'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - script: dotnet restore $(apiProject)
      displayName: 'Restore Dependencies'

    - script: dotnet build $(apiProject) --configuration $(buildConfiguration) --no-restore
      displayName: 'Build Project'

    - script: dotnet publish $(apiProject) --configuration $(buildConfiguration) --output $(publishOutputApiProject) --no-build
      displayName: 'Publish Project'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(publishOutputApiProject)'
        ArtifactName: 'dropApi'

    - script: dotnet restore $(functionAppProject)
      displayName: 'Restore Dependencies'

    - script: dotnet build $(functionAppProject) --configuration $(buildConfiguration) --no-restore
      displayName: 'Build Function App'

    - script: dotnet publish $(functionAppProject) --configuration $(buildConfiguration) --output $(publishOutputFunctionProject) --no-build
      displayName: 'Publish Function App'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(publishOutputFunctionProject)'
        ArtifactName: 'dropFunction'

- stage: DevDeploy
  displayName: 'Dev Deploy'
  dependsOn: DevBuild
  condition: |
    and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

  jobs:
  - deployment: DeployWebApp
    environment: 'Dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: dropApi

          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'gamer-uncle-dev-sc'
              appType: 'webApp'
              appName: 'gamer-uncle-dev-app-svc'
              package: '$(Pipeline.Workspace)/dropApi'

  - deployment: DeployFunctionApp
    environment: 'Dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: dropFunction

          - task: AzureCLI@2
            displayName: 'Configure Function App Settings'
            inputs:
              azureSubscription: 'gamer-uncle-dev-sc'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Setting Function App application settings..."
                az functionapp config appsettings set \
                  --name gamer-uncle-dev-function \
                  --resource-group gamer-uncle-dev-rg \
                  --settings \
                    'COSMOS_ENDPOINT=https://gamer-uncle-dev-cosmos.documents.azure.com:443/' \
                    'AZURE_TENANT_ID=c88223a3-60b3-4697-9374-209fc154bdf1' \
                    'AZURE_CLIENT_ID=ed29ac5e-cee9-4607-b564-c858738b2e62' \
                    'SyncGameCount=10'
                
                echo "Verifying settings were applied..."
                az functionapp config appsettings list \
                  --name gamer-uncle-dev-function \
                  --resource-group gamer-uncle-dev-rg \
                  --query "[?name=='COSMOS_ENDPOINT' || name=='AZURE_TENANT_ID' || name=='SyncGameCount']" \
                  -o table

          - task: AzureFunctionApp@1
            displayName: 'Deploy Function App (Consumption Linux)'
            inputs:
              azureSubscription: 'gamer-uncle-dev-sc'
              appType: 'functionAppLinux'
              appName: 'gamer-uncle-dev-function'
              package: '$(Pipeline.Workspace)/dropFunction'
              runtimeStack: 'DOTNET-ISOLATED|8.0'

          - task: AzureCLI@2
            displayName: 'Verify and Trigger Function'
            inputs:
              azureSubscription: 'gamer-uncle-dev-sc'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Waiting for Function App to be ready after deployment..."
                sleep 60
                
                echo "Checking Function App status..."
                az functionapp show \
                  --name gamer-uncle-dev-function \
                  --resource-group gamer-uncle-dev-rg \
                  --query "{state:state,runtime:linuxFxVersion,kind:kind}" -o table
                
                echo "Listing deployed functions..."
                FUNCTIONS=$(az functionapp function list \
                  --name gamer-uncle-dev-function \
                  --resource-group gamer-uncle-dev-rg \
                  --query "[].name" -o tsv 2>/dev/null || echo "")
                
                if [[ -z "$FUNCTIONS" ]]; then
                  echo "❌ No functions found. Waiting and retrying..."
                  sleep 30
                  FUNCTIONS=$(az functionapp function list \
                    --name gamer-uncle-dev-function \
                    --resource-group gamer-uncle-dev-rg \
                    --query "[].name" -o tsv 2>/dev/null || echo "")
                fi
                
                if [[ -z "$FUNCTIONS" ]]; then
                  echo "❌ No functions deployed! Check deployment logs"
                  exit 1
                else
                  echo "✅ Found functions: $FUNCTIONS"
                fi
                
                # Get function key
                echo "Getting Function App host key..."
                HOST_KEY=$(az functionapp keys list \
                  --name gamer-uncle-dev-function \
                  --resource-group gamer-uncle-dev-rg \
                  --query "masterKey" -o tsv)
                
                if [[ -z "$HOST_KEY" ]]; then
                  echo "❌ Could not get function key"
                  exit 1
                fi
                
                # Trigger function if it exists
                if [[ "$FUNCTIONS" == *"GameSyncHttpStart"* ]]; then
                  echo "✅ GameSyncHttpStart function found, triggering..."
                  
                  RESPONSE=$(curl -s -X POST \
                    "https://gamer-uncle-dev-function.azurewebsites.net/api/GameSyncHttpStart?code=$HOST_KEY" \
                    -H "Content-Type: application/json" \
                    -d '{}' \
                    -w "\nHTTP_CODE:%{http_code}" \
                    --include)
                  
                  echo "Response:"
                  echo "$RESPONSE"
                  
                  HTTP_CODE=$(echo "$RESPONSE" | grep -o "HTTP_CODE:[0-9]*" | cut -d: -f2)
                  
                  if [[ "$HTTP_CODE" == "2"* ]]; then
                    echo "✅ Function triggered successfully!"
                  else
                    echo "❌ Function trigger failed with status: $HTTP_CODE"
                    exit 1
                  fi
                else
                  echo "❌ GameSyncHttpStart function not found"
                  echo "Available functions: $FUNCTIONS"
                  exit 1
                fi
