trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  apiProject: 'services/api/GamerUncle.Api.csproj'
  functionAppProject: 'services/functions/GamerUncle.Function.BggSync/GamerUncle.Function.BggSync.csproj'
  publishOutputApiProject: '$(Build.ArtifactStagingDirectory)/publish/api'
  publishOutputFunctionProject: '$(Build.ArtifactStagingDirectory)/publish/function'

stages:
- stage: DevBuild
  displayName: 'Dev Build'
  jobs:
  - job: BuildJob
    displayName: 'Build and Publish Artifacts'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - script: dotnet restore $(apiProject)
      displayName: 'Restore Dependencies'

    - script: dotnet build $(apiProject) --configuration $(buildConfiguration) --no-restore
      displayName: 'Build Project'

    - script: dotnet publish $(apiProject) --configuration $(buildConfiguration) --output $(publishOutputApiProject) --no-build
      displayName: 'Publish Project'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(publishOutputApiProject)'
        ArtifactName: 'dropApi'

    - script: dotnet restore $(functionAppProject)
      displayName: 'Restore Dependencies'

    - script: dotnet build $(functionAppProject) --configuration $(buildConfiguration) --no-restore
      displayName: 'Build Function App'

    - script: dotnet publish $(functionAppProject) --configuration $(buildConfiguration) --output $(publishOutputFunctionProject) --no-build
      displayName: 'Publish Function App'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(publishOutputFunctionProject)'
        ArtifactName: 'dropFunction'

- stage: DevDeploy
  displayName: 'Dev Deploy'
  dependsOn: DevBuild
  condition: |
    and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

  jobs:
  - deployment: DeployWebApp
    environment: 'Dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: dropApi

          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'gamer-uncle-dev-sc'
              appType: 'webApp'
              appName: 'gamer-uncle-dev-app-svc'
              package: '$(Pipeline.Workspace)/dropApi'

  - deployment: DeployFunctionApp
    environment: 'Dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: dropFunction

          - task: AzureFunctionApp@1
            inputs:
              azureSubscription: 'gamer-uncle-dev-sc'
              appType: 'functionApp'
              appName: 'gamer-uncle-dev-function'
              package: '$(Pipeline.Workspace)/dropFunction'
              deploymentMethod: 'auto'
