# Auto-generated by testit - local dev build launcher (safe to delete)
$ErrorActionPreference = 'Stop'

$env:JAVA_HOME = 'C:\Program Files\Android\Android Studio\jbr'
$env:ANDROID_HOME = Join-Path $env:LOCALAPPDATA 'Android\Sdk'
$env:ANDROID_SDK_ROOT = $env:ANDROID_HOME
$env:Path = "$env:JAVA_HOME\bin;$env:ANDROID_HOME\platform-tools;$env:Path"

Set-Location 'C:\Users\rajsin\r\Code\gamer-uncle\apps\mobile'

Write-Host 'JAVA_HOME    = ' $env:JAVA_HOME -ForegroundColor Cyan
Write-Host 'ANDROID_HOME = ' $env:ANDROID_HOME -ForegroundColor Cyan
Write-Host 'Building local debuggable dev APK via expo run:android ...' -ForegroundColor Cyan
Write-Host '(First run does expo prebuild + Gradle; this takes several minutes.)' -ForegroundColor DarkGray

npx expo run:android
